membersrvc:

  image: hyperledger/fabric-membersrvc:latest
  restart: unless-stopped
  expose:
    - "7054"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: membersrvc 
    vp0:
      extends:
        file: peer-noops.yml
        service: vp
      hostname: vp0
      environment:
        - CORE_PEER_ID=vp0
        - CORE_SECURITY_ENABLED=true
        - CORE_SECURITY_ENROLLID=test_vp0
        - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
        - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
        - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
        - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
      ports:
        - "7050:7050"
        - "7051:7051"
      links:
        - membersrvc
      command: sh -c "sleep 5; peer node start"


